name: random_nap_generator
description: An app for generating random calendar events - the naps
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.0-152.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  permission_handler: ^11.1.0
  table_calendar: ^3.0.9
  add_2_calendar: ^3.0.1
  flutter_local_notifications:
  flutter_localizations:
    sdk: flutter
  shared_preferences:
  url_launcher:

flutter_icons:
  image_path: 'assets/images/sleeping.png'
  android: true
  ios: true

dev_dependencies:
  flutter_launcher_icons:
  intl_translation: ^0.18.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - lib/l10n/app_en.arb

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Medium.ttf